config/routes.rb
Parttimers::Application.routes.draw do
  root :to => 'attendances#index'

  get "welcome/index"

  resources :attendances

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :attendances, :dependent => :destroy

  def to_s
    "#{ email }"
  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  # just_define_datetime_picker :date, :add_to_attr_accessible => true
  just_define_time_picker :from, :add_to_attr_accessible => true
  just_define_time_picker :to, :add_to_attr_accessible => true

  attr_accessible :date, :from, :to, :admin_user_id
  attr_accessible :presence, :message, :priority, :frequency

  validates :date, :presence => true

  validates :from, :presence => true

  validates :to, :presence => true

  validates :presence,
    :inclusion => [ 'present', 'absent', 'not sure' ],
    :presence => true

  validates :priority,
    :inclusion => %w(urgent medium low),
    :presence => true

  # TODO: validate if `to` is later than `from`

  #validates :frequency,
    # :inclusion => %w(daily weekly monthly yearly),
    #:presence => false

  belongs_to :admin_user

  after_initialize :set_default_values

  def frequency_to_num
    translate_dictionary = {
        'daily' => 1,
        'weekly' => 2,
        'monthly' => 3,
        'yearly' => 4
    }

    translate_dictionary[frequency] or 0
  end

  def priority_to_num
    translate_dictionary = {
        'low' => 1,
        'medium' => 2,
        'urgent' => 3
    }

    translate_dictionary[priority] or 0
  end

  protected

  def set_default_values
    presence = 'present'
    priority = 'low'
    frequency = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendances_controller.rb
class AttendancesController < InheritedResources::Base
    before_filter :set_user, :only => [ :index ]

    protected

    def set_user
        if params[:user].present?
            @user = AdminUser.find_by_email(params[:user])
        end

        @user ||= current_admin_user
        @user ||= AdminUser.first

        if @user.blank?
            redirect_to 'admin/dashboard#index'
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.time_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.time_select :to %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<div>You're browsing attendance plan for <i><%= @user.email %></i></div>

<% if @user.attendances.blank? %>
  <br />
  <div>No plans are set yet</div>
<% else %>
  <script type="text/javascript">
  $(document).ready(function() {
      var events_array = [
        <% @user.attendances.map do |attendance| %>
          {
              startDate: new Date(<%= [attendance.date.year, attendance.date.month - 1, attendance.date.day, attendance.from_hour, attendance.from_minute].join ', ' %>),
              <% if attendance.frequency_to_num == 0 %>
              endDate: new Date(<%= [attendance.date.year, attendance.date.month - 1, attendance.date.day, attendance.to_hour, attendance.to_minute].join ', ' %>),
              <% end %>
              title: "<%= attendance.presence %>",
              description: "<%= attendance.message %>",
              priority: <%= attendance.priority_to_num %>, // 1 = Low, 2 = Medium, 3 = Urgent
              frecuency: <%= attendance.frequency_to_num %> // 1 // 1 = Daily, 2 = Weekly, 3 = Monthly, 4 = Yearly
          },
        <% end %>
      ];

      jQuery("#calendar").dp_calendar({
          events_array: events_array
      });
  });
  </script>

  <br />

  <div id="calendar"></div>
<% end %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @attendance.from %>
</p>

<p>
  <b>To:</b>
  <%= @attendance.to %>
</p>

<p>
  <b>Date:</b>
  <%= @attendance.date %>
</p>


<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parttimers</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<span>Choose which user you wish to watch:</span>